[package]
name = "xtask"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1"
git-version = "0.3"
sha2 = "0.10"
tar = "0.4"