[package]
name = "timetag"
version = "0.1.0"
authors = ["Bob Peterson <bob@rwp.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.49"

[build-dependencies]
cxx-build = "1.0.49"