[package]
name = "tagger_capnp"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capnp = "0.14.2"
capnp-rpc = "0.14.1"